apiVersion: v1
kind: Service
metadata:
  name: laravel-web
  namespace: default
  labels:
    app: laravel
    tier: web
spec:
  selector:
    app: laravel
    tier: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
