apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-redis-trigger-auth
  namespace: default
spec:
  secretTargetRef:
    - parameter: password
      name: laravel-secrets
      key: REDIS_PASSWORD
